### ISSUE TITLE
recently started getting issues

### ISSUE THREAD

**Issue by DuncanFaulkner** [jamesgeorge007/jamesgeorge007#3]
Not sure why but this is only just started happening (for this example I have replaced my actual username with the word username).

Run jamesgeorge007/github-activity-readme@master
  with:
    GH_USERNAME: <actual user name removed>
    COMMIT_MSG: :zap: Update README with the recent activity
    MAX_LINES: 5
  env:
    GITHUB_TOKEN: ***
⬤  debug     Getting activity for username
⬤  debug     Activity for username, 9 events found.
ℹ  info      Found less than 5 activities
✔  success   Updated README with the recent activity
⬤  debug     Something went wrong
✖  fatal     Error: Invalid status code: 1 
    at ChildProcess.<anonymous> (/home/runner/work/_actions/jamesgeorge007/github-activity-readme/master/dist/index.js:1530:15)
    at ChildProcess.emit (events.js:314:[2](https://github.com/username/username/runs/6460238301?check_suite_focus=true#step:3:2)0)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:[3](https://github.com/username/username/runs/6460238301?check_suite_focus=true#step:3:3)1[4](https://github.com/username/username/runs/6460238301?check_suite_focus=true#step:3:4):20)
    at Pipe.<anonymous> (net.js:67[5](https://github.com/username/username/runs/6460238301?check_suite_focus=true#step:3:5):[12](https://github.com/username/username/runs/6460238301?check_suite_focus=true#step:3:12))

**Comment by DuncanFaulkner** [comment]
sorry wrong repo - closing as now working
